server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Reverse proxy API calls -> your backend
  location /api/ {
    proxy_pass https://clientinsight-api-staging.fly.dev/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # SPA routing
  location / {
    try_files $uri $uri/ /index.html;
  }
}
